# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainoo.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1188, 450)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.qc = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.qc.setGeometry(QtCore.QRect(150, 50, 104, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.qc.setFont(font)
        self.qc.setPlainText("")
        self.qc.setObjectName("qc")
        self.mcmj = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.mcmj.setGeometry(QtCore.QRect(150, 120, 104, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.mcmj.setFont(font)
        self.mcmj.setObjectName("mcmj")
        self.qg = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.qg.setGeometry(QtCore.QRect(150, 190, 104, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.qg.setFont(font)
        self.qg.setObjectName("qg")
        self.qk = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.qk.setGeometry(QtCore.QRect(150, 260, 104, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.qk.setFont(font)
        self.qk.setObjectName("qk")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 50, 51, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(90, 260, 51, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(90, 190, 51, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 120, 91, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.hntrz = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.hntrz.setGeometry(QtCore.QRect(520, 50, 104, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.hntrz.setFont(font)
        self.hntrz.setPlainText("")
        self.hntrz.setObjectName("hntrz")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(370, 50, 141, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.mhrz = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.mhrz.setGeometry(QtCore.QRect(520, 120, 104, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.mhrz.setFont(font)
        self.mhrz.setPlainText("")
        self.mhrz.setObjectName("mhrz")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(340, 120, 161, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.mhhd = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.mhhd.setGeometry(QtCore.QRect(520, 190, 104, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.mhhd.setFont(font)
        self.mhhd.setPlainText("")
        self.mhhd.setObjectName("mhhd")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(340, 190, 161, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.fsclrz = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.fsclrz.setGeometry(QtCore.QRect(520, 260, 104, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.fsclrz.setFont(font)
        self.fsclrz.setPlainText("")
        self.fsclrz.setObjectName("fsclrz")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(360, 260, 141, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(360, 330, 141, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.fsclhd = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.fsclhd.setGeometry(QtCore.QRect(520, 330, 104, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.fsclhd.setFont(font)
        self.fsclhd.setPlainText("")
        self.fsclhd.setObjectName("fsclhd")
        self.lk = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.lk.setGeometry(QtCore.QRect(150, 330, 104, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lk.setFont(font)
        self.lk.setObjectName("lk")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(40, 330, 101, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(720, 50, 151, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.zsclrz = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.zsclrz.setGeometry(QtCore.QRect(880, 50, 104, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.zsclrz.setFont(font)
        self.zsclrz.setPlainText("")
        self.zsclrz.setObjectName("zsclrz")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(720, 120, 141, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.zsclhd = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.zsclhd.setGeometry(QtCore.QRect(880, 120, 104, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.zsclhd.setFont(font)
        self.zsclhd.setPlainText("")
        self.zsclhd.setObjectName("zsclhd")
        self.ksjs = QtWidgets.QPushButton(self.centralwidget)
        self.ksjs.setGeometry(QtCore.QRect(860, 250, 121, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.ksjs.setFont(font)
        self.ksjs.setObjectName("ksjs")
        self.jsjg = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.jsjg.setGeometry(QtCore.QRect(840, 310, 161, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.jsjg.setFont(font)
        self.jsjg.setObjectName("jsjg")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(740, 310, 91, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1188, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "墙长"))
        self.label_2.setText(_translate("MainWindow", "墙宽"))
        self.label_3.setText(_translate("MainWindow", "墙高"))
        self.label_4.setText(_translate("MainWindow", "门窗面积"))
        self.label_5.setText(_translate("MainWindow", "墙体材料容重"))
        self.label_6.setText(_translate("MainWindow", "内外墙抹灰容重"))
        self.label_7.setText(_translate("MainWindow", "内外墙抹灰厚度"))
        self.label_8.setText(_translate("MainWindow", "防水材料容重"))
        self.label_9.setText(_translate("MainWindow", "防水材料厚度"))
        self.label_10.setText(_translate("MainWindow", "门窗重量"))
        self.label_11.setText(_translate("MainWindow", "装饰材料容重"))
        self.label_12.setText(_translate("MainWindow", "装饰材料厚度"))
        self.ksjs.setText(_translate("MainWindow", "开始计算"))
        self.label_13.setText(_translate("MainWindow", "计算结果"))

